name: kana_master
description: "Simple app to learn basics of japanese language."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Router
  go_router: ^17.0.1
  # DI
  injectable: ^2.7.1+4
  get_it: ^9.2.0
  # Bloc
  flutter_bloc: ^9.1.1
  # Database
  sqflite: ^2.4.2
  # Image management
  image: ^4.7.2
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.2.1
  file_picker: ^10.3.8
  csv: ^6.0.0
  # Charts
  fl_chart: ^1.1.1
  # CNN model
  tflite_flutter: ^0.12.1
  # SVG stroke order
  flutter_svg: ^2.0.10
  path_drawing: ^1.0.1
  xml: ^6.5.0
  # tflite_flutter:
  #   git:
  #       url: https://github.com/CaptainDario/flutter-tflite

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.10.4
  injectable_generator: ^2.12.0

  # App icon
  flutter_launcher_icons: ^0.14.4

  # Splash screen
  flutter_native_splash: ^2.4.7

  # Change app package name
  change_app_package_name: ^1.4.0 # flutter pub run change_app_package_name:main com.agasco.kanamaster

flutter_icons:
  android: "kana_master"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true

  #color: "#000000"
  background_image: "assets/splash/background.png"
  image: "assets/splash/splash_white_640.png"
  branding: "assets/splash/cidenaris_logo.png"

  branding_bottom_padding_ios: 35

  android_12:
    color: "#000000"
    image: "assets/splash/splash_white_1200.png"
    branding: "assets/splash/cidenaris_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/hiragana/
    - assets/svg/katakana/
    - assets/csv/kanji_data.csv
    - assets/models/model_etl8g.tflite
    - assets/models/hiragana.tflite
    - assets/models/katakana.tflite
